image: maven:3-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

before_script:
  - mvn clean

stages:
  - build

cache:
  paths:
    - .m2/

build:
  stage: build
  script:
    - echo "<settings><servers><server><id>ftp-repository</id><username>$FTP_USERNAME</username><password>$FTP_PASSWORD</password></server></servers></settings>" > /root/.m2/settings.xml
    - mvn package
    - mv $CI_PROJECT_DIR/target/*.jar $CI_PROJECT_DIR/
    - if [ -n "$FTP_USERNAME" ]; then mvn wagon:upload; fi
  artifacts:
    name: $CI_PROJECT_NAME
    paths:
    - ./*.jar