image: maven:3-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

before_script:
  - mvn clean

stages:
  - build

cache:
  paths:
    - .m2/

build:
  stage: build
  script:
    - mvn package
    - cp $CI_PROJECT_DIR/target/*.jar $CI_PROJECT_DIR/
  artifacts:
    name: $CI_PROJECT_NAME
    paths:
    - ./*.jar
