image: maven:3-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

before_script:
  - mvn clean

stages:
  - build

cache:
  paths:
    - .m2/

build:
  stage: build
  script:
    - mvn package
  tags:
    - maven
  artifacts:
    name: "PluginName"
    paths:
    - target/*.jar
