# Change main and author as needed
main: me.jeeeeef.awarefix.AwareFix
author: Jeeeeef
api-version: 1.13

# Automatically filled in at build time, DO NOT CHANGE
name: ${project.name}
version: ${project.version}
description: ${project.description}

# Register commands
commands:
    fixaware:
      description: Fix awareness of entities in current chunk.
      usage: /fixaware
      permission: fixaware.use
