main: com.package.name.pluginpackage.MainClass
author: ExampleAuthor

name: ${project.name}
version: ${project.version}
description: ${project.description}

commands:
    commandname:
      description: This is a demo command.
      usage: /<command> [player]